# Generated by Django 4.2.5 on 2023-09-13 23:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('employee_specializations', '0002_remove_employeespecialization_specialization_source'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vacancies',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('placement', models.CharField(choices=[('OF', 'Office'), ('RM', 'Remotely'), ('FL', 'Flexible')], max_length=20)),
                ('busyness', models.CharField(choices=[('PT', 'part time'), ('FT', 'full time')], max_length=20)),
                ('comment', models.TextField()),
                ('specialization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='employee_specializations.employeespecialization')),
            ],
        ),
    ]
