# Generated by Django 4.2.5 on 2023-09-13 23:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vacancies', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vacancies',
            name='busyness',
            field=models.CharField(choices=[('Part time', 'PT'), ('Full time', 'FT')], max_length=20),
        ),
        migrations.AlterField(
            model_name='vacancies',
            name='placement',
            field=models.CharField(choices=[('Office', 'OF'), ('Remotely', 'RM'), ('Flexible', 'FL')], max_length=20),
        ),
    ]
