# Generated by Django 4.2.5 on 2023-09-14 04:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vacancies', '0002_alter_vacancies_busyness_alter_vacancies_placement'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='vacancies',
            options={'verbose_name_plural': 'Vacancies'},
        ),
    ]
