# Generated by Django 4.2.5 on 2023-09-09 10:40

import uuid

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("orders", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="order_code",
            field=models.UUIDField(default=uuid.UUID("28643079-80a1-43fc-b05a-9a2f5f46b5f3")),
        ),
    ]
