# Generated by Django 4.2.5 on 2023-09-09 11:04

import uuid

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("orders", "0002_alter_order_order_code"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="order_code",
            field=models.UUIDField(default=uuid.UUID("70b4efbf-44e1-4444-abb3-783ecd1bab4a"), unique=True),
        ),
    ]
