# Generated by Django 4.2.5 on 2023-09-09 17:05

import uuid

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("clients", "0005_clientinfo_age_clientinfo_check_client_age"),
        ("orders", "0003_alter_order_order_code"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="client_data",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="order",
                to="clients.clientinfo",
            ),
        ),
        migrations.AlterField(
            model_name="order",
            name="order_code",
            field=models.UUIDField(default=uuid.UUID("9d2e5dbe-24d7-44ae-952f-a11bb51c6d80"), unique=True),
        ),
    ]
