# Generated by Django 4.2.5 on 2023-09-09 17:06

import uuid

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("orders", "0004_alter_order_client_data_alter_order_order_code"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="order_code",
            field=models.UUIDField(default=uuid.UUID("49ce25bd-b87a-4ab3-85a2-83367e29cc94"), unique=True),
        ),
    ]
