# Generated by Django 4.2.5 on 2023-09-09 17:11

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("orders", "0005_alter_order_order_code"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="order_code",
            field=models.UUIDField(unique=True),
        ),
    ]
