# Generated by Django 4.2.5 on 2023-09-11 18:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("clients", "0006_client"),
        ("orders", "0006_alter_order_order_code"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="client_data",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="order",
                to="clients.client",
            ),
        ),
    ]
