# Generated by Django 4.2.5 on 2023-09-14 03:41

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("orders", "0007_alter_order_client_data"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="cost",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
            preserve_default=False,
        ),
    ]
