# Generated by Django 4.2.5 on 2023-09-22 00:40

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("orders", "0008_order_cost"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="cleaners",
            field=models.ManyToManyField(related_name="orders", to=settings.AUTH_USER_MODEL),
        ),
    ]
