# Generated by Django 4.2.5 on 2023-09-07 08:06

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("clients", "0001_initial"),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="clientinfo",
            constraint=models.CheckConstraint(
                check=models.Q(
                    models.Q(("is_individual", True), ("is_juridical", False)),
                    models.Q(("is_individual", False), ("is_juridical", True)),
                    _connector="OR",
                ),
                name="check_juridical_status",
            ),
        ),
    ]
