# Generated by Django 4.2.5 on 2023-09-07 08:40

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("clients", "0002_clientinfo_check_juridical_status"),
    ]

    operations = [
        migrations.AlterField(
            model_name="clientinfo",
            name="company_name",
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name="clientinfo",
            name="contact_phone",
            field=models.CharField(max_length=19),
        ),
        migrations.AddConstraint(
            model_name="clientinfo",
            constraint=models.CheckConstraint(
                check=models.Q(
                    (
                        "contact_phone__regex",
                        "^+375 ((17|29|33|44)) [0-9]{3}-[0-9]{2}-[0-9]{2}$",
                    )
                ),
                name="regex_contact_phone",
            ),
        ),
    ]
