# Generated by Django 4.2.5 on 2023-09-07 09:11

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("clients", "0003_alter_clientinfo_company_name_and_more"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="clientinfo",
            name="regex_contact_phone",
        ),
        migrations.AddConstraint(
            model_name="clientinfo",
            constraint=models.CheckConstraint(
                check=models.Q(
                    (
                        "contact_phone__regex",
                        "^\\+375 \\((17|29|33|44)\\) [0-9]{3}-[0-9]{2}-[0-9]{2}$",
                    )
                ),
                name="regex_contact_phone",
            ),
        ),
    ]
