# Generated by Django 4.2.5 on 2023-09-07 21:48

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("clients", "0004_remove_clientinfo_regex_contact_phone_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="clientinfo",
            name="age",
            field=models.IntegerField(default=18),
            preserve_default=False,
        ),
        migrations.AddConstraint(
            model_name="clientinfo",
            constraint=models.CheckConstraint(check=models.Q(("age__gte", 18)), name="check_client_age"),
        ),
    ]
