# Generated by Django 4.2.5 on 2023-09-11 18:09

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("clients", "0005_clientinfo_age_clientinfo_check_client_age"),
    ]

    operations = [
        migrations.CreateModel(
            name="Client",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("first_name", models.CharField(max_length=50)),
                ("last_name", models.CharField(max_length=50)),
                ("surname", models.CharField(max_length=50)),
                ("age", models.IntegerField()),
            ],
        ),
    ]
