# Generated by Django 4.2.5 on 2023-09-11 18:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("orders", "0007_alter_order_client_data"),
        ("clients", "0006_client"),
        ("companies", "0001_initial"),
        ("services", "0005_alter_service_client"),
    ]

    operations = [
        migrations.DeleteModel(
            name="ClientInfo",
        ),
        migrations.AddField(
            model_name="client",
            name="company",
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to="companies.company"),
        ),
        migrations.AddConstraint(
            model_name="client",
            constraint=models.CheckConstraint(check=models.Q(("age__gte", 18)), name="check_client_age"),
        ),
    ]
