# Generated by Django 4.2.5 on 2023-10-11 22:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='new',
            name='short_description',
            field=models.CharField(max_length=200),
        ),
    ]
