# Generated by Django 4.2.5 on 2023-10-11 22:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_alter_new_short_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='new',
            name='short_description',
            field=models.CharField(max_length=100),
        ),
    ]
