# Generated by Django 4.2.5 on 2023-09-11 18:09

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Company",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("subscription_date", models.DateField(auto_now_add=True)),
                ("is_juridical", models.BooleanField(default=False)),
                ("is_individual", models.BooleanField(default=False)),
                ("contact_phone", models.CharField(max_length=19)),
                ("company_name", models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.AddConstraint(
            model_name="company",
            constraint=models.CheckConstraint(
                check=models.Q(
                    models.Q(("is_individual", True), ("is_juridical", False)),
                    models.Q(("is_individual", False), ("is_juridical", True)),
                    _connector="OR",
                ),
                name="check_juridical_status",
            ),
        ),
        migrations.AddConstraint(
            model_name="company",
            constraint=models.CheckConstraint(
                check=models.Q(
                    (
                        "contact_phone__regex",
                        "^\\+375 \\((17|29|33|44)\\) [0-9]{3}-[0-9]{2}-[0-9]{2}$",
                    )
                ),
                name="regex_contact_phone",
            ),
        ),
    ]
