# Generated by Django 4.2.5 on 2023-09-09 17:21

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("orders", "0006_alter_order_order_code"),
        ("services", "0002_service_client"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="service",
            name="order",
        ),
        migrations.AddField(
            model_name="service",
            name="order",
            field=models.ManyToManyField(null=True, related_name="services", to="orders.order"),
        ),
    ]
