# Generated by Django 4.2.5 on 2023-09-10 20:35

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("orders", "0006_alter_order_order_code"),
        ("services", "0003_remove_service_order_service_order"),
    ]

    operations = [
        migrations.AlterField(
            model_name="service",
            name="order",
            field=models.ManyToManyField(related_name="services", to="orders.order"),
        ),
    ]
