# Generated by Django 4.2.5 on 2023-09-11 18:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("clients", "0006_client"),
        ("services", "0004_alter_service_order"),
    ]

    operations = [
        migrations.AlterField(
            model_name="service",
            name="client",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="services",
                to="clients.client",
            ),
        ),
    ]
