# Generated by Django 4.2.5 on 2023-09-21 23:10

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("services", "0005_alter_service_client"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="service",
            name="cost",
        ),
    ]
