# Generated by Django 4.2.5 on 2023-09-21 23:10

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("service_types", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="servicetype",
            name="cost",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
            preserve_default=False,
        ),
    ]
