# Generated by Django 4.2.5 on 2023-09-14 01:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Promocodes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('is_archived', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('conditions', models.TextField()),
                ('start_date', models.DateTimeField()),
                ('finish_date', models.DateTimeField()),
            ],
        ),
        migrations.AddConstraint(
            model_name='promocodes',
            constraint=models.CheckConstraint(check=models.Q(('start_date__lt', models.F('finish_date'))), name='promocode_check_dates'),
        ),
    ]
