# Generated by Django 4.2.5 on 2023-09-14 04:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('promocodes', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='promocodes',
            options={'verbose_name_plural': 'Promocodes'},
        ),
    ]
