# Generated by Django 4.2.5 on 2023-11-20 09:32

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("promocodes", "0002_alter_promocodes_options"),
    ]

    operations = [
        migrations.AddField(

            model_name="promocodes",
            name="percent",
            field=models.IntegerField(
                default=0,
                validators=[
                    django.core.validators.MinValueValidator(1),
                    django.core.validators.MaxValueValidator(100),
                ],
            ),
        )
    ]
