# Generated by Django 4.2.5 on 2023-11-20 11:04

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('promocodes', '0003_promocodes_percent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='promocodes',
            name='percent',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(100)]),
        ),
    ]
