# Generated by Django 4.2.5 on 2023-09-07 00:19

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("service_types", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="EmployeeSpecialization",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("specialization_source", models.CharField(max_length=100)),
                (
                    "service_types",
                    models.ManyToManyField(related_name="specializations", to="service_types.servicetype"),
                ),
            ],
        ),
    ]
