# Generated by Django 4.2.5 on 2023-09-07 23:01

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("employee_specializations", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="employeespecialization",
            name="specialization_source",
        ),
    ]
