# Generated by Django 4.2.5 on 2023-09-13 20:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('test', models.TextField()),
                ('added_at', models.DateTimeField(auto_now_add=True)),
                ('to_show_answer', models.BooleanField(default=False)),
                ('answer', models.TextField(null=True)),
            ],
        ),
    ]
