# Generated by Django 4.2.5 on 2023-09-07 09:20

import datetime

import django.db.models.expressions
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("employees", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="employee",
            options={},
        ),
        migrations.AddConstraint(
            model_name="employee",
            constraint=models.CheckConstraint(
                check=models.Q(
                    (
                        "applied_at__gt",
                        django.db.models.expressions.CombinedExpression(
                            models.F("date_of_birth"),
                            "+",
                            models.Value(datetime.timedelta(days=6048)),
                        ),
                    )
                ),
                name="check_employee_age",
            ),
        ),
    ]
