# Generated by Django 4.2.5 on 2023-09-21 21:29

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("employees", "0004_employee_image_alter_employee_email"),
    ]

    operations = [
        migrations.AddField(
            model_name="employee",
            name="role",
            field=models.CharField(
                choices=[("MANAGER", "Manager"), ("CLEANER", "Cleaner")],
                default="MANAGER",
                max_length=50,
            ),
            preserve_default=False,
        ),
    ]
