# Generated by Django 4.2.5 on 2023-09-21 21:30

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("employees", "0005_employee_role"),
    ]

    operations = [
        migrations.AlterField(
            model_name="employee",
            name="role",
            field=models.CharField(
                choices=[("MANAGER", "Manager"), ("CLEANER", "Cleaner")],
                max_length=50,
                null=True,
            ),
        ),
    ]
