# Generated by Django 4.2.5 on 2023-09-22 00:40

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("employees", "0006_alter_employee_role"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="employee",
            name="orders",
        ),
    ]
